gerenciamento_pet/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pet_app/', include('pet_app.urls')),
]

pet_app/urls.py
from django.urls import path

from pet_app.models import contato_models
from .views import cliente_views, pet_views, consulta_views, funcionario_views, autenticacao_views, dashboard_views, contato_views
from django.contrib import admin
from django.urls import path
from .views import site_views

urlpatterns = [
    #----------------------urls de clientes
    path    ('cadastrar_cliente',           cliente_views.cadastrar_cliente,            name='cadastrar_cliente'),
    path    ('listar_clientes',             cliente_views.listar_clientes,              name='listar_clientes'),
    path    ('listar_cliente/<int:id>',     cliente_views.listar_cliente_id,            name='listar_cliente'),
    path    ('remover_cliente/<int:id>',    cliente_views.remover_cliente,              name='remover_cliente'), 
    path    ('editar_cliente/<int:id>',     cliente_views.editar_cliente,               name='editar_cliente'),
    
    #-----------------------urls de pets
    path    ('cadastrar_pet/<int:id>',      pet_views.inserir_pet,                      name='cadastrar_pet'),
    path    ('listar_pet/<int:id>',         pet_views.listar_pet_id,                    name='listar_pet_id'),
    path    ('listar_pets',                 pet_views.listar_pets,                      name='listar_pets'),

    #-----------------------urls de consultas
    path    ('cadastrar_consulta/<int:id>', consulta_views.inserir_consulta,            name='cadastrar_consulta'),
    path    ('lista_consulta/<int:id>',     consulta_views.listar_consulta_id,          name='listar_consulta_id'),
    
    #-----------------------urls de funcionarios
    path    ('cadastrar_funcionario',       funcionario_views.inserir_funcionario,      name='cadastrar_funcionario'),
    path    ('listar_funcionarios',         funcionario_views.listar_funcionarios,      name='listar_funcionarios'),
    path    ('login',                       autenticacao_views.login_usuario,           name='login'),
    path    ('logout',                      autenticacao_views.deslogar_usuario,        name='logout'),
    path    ('dashboard',                   dashboard_views.dashboard,                  name='dashboard'),   

    #-----------------------urls do site
    path('home', site_views.index, name='home'),
    path('sobre', site_views.sobre, name='sobre'),
    path('servicos', site_views.servicos, name='servicos'),
    path('listar_contatos', contato_views.listar_contatos, name='listar_contatos'),
    path('cadastrar_contatos', contato_views.cadastrar_contato, name='cadastrar_contatos'),
    path('lista_contato_id/<int:id>', contato_views.listar_contato_id, name='lista_contato_id'),       
]

pet_app/models/consulta_models.py
from django.db import models
from django.db.models.deletion import CASCADE
from pet_app.models.pet_models import Pet



class ConsultaPet(models.Model):
    DOUTOR_CHOICES = (
        ('Ma', 'Maria Lima'),
        ('Fc', 'Fernanda Cardoso Lira'),
        ('Af', 'Amanda Finamor'),
        ('Vm', 'Victoria Misson'),
        ('As', 'Amanda dos Santos Silva'),
        ('Cv', 'Cássia Vasconcellos'),
        ('Rp', 'Regina Elis Pascoal'),
    )

    ESPECIALIDADES_CHOICES = (
        ('Cg', 'Clinico Geral'),
        ('Cd', 'Cardiologia'),
        ('De', 'Dermatologia'),
        ('Fi', 'Fisioterapia'),
        ('He', 'Hematologia'),
        ('Ne', 'Neurologia'),
        ('Or', 'Ortopedia'),
    )

    pet                 =       models.ForeignKey   (   Pet, on_delete=CASCADE, null=False, blank=False     )
    data                =       models.DateField    (   null=False, blank=False, auto_now_add=True          )
    doutor              =       models.CharField    (   max_length=2, choices=DOUTOR_CHOICES, blank=True, null=True )
    motivo_consulta     =       models.CharField    (   max_length=200, null=False, blank=False )
    medicamento_atual   =       models.TextField    (   null=False, blank=False )
    medicamentos_prescritos =   models.TextField    (   null=False, blank=False )
    exames              =       models.TextField    (   null=False, blank=False )
    especialidade       =       models.CharField    (   max_length=2, choices=ESPECIALIDADES_CHOICES, blank=True, null=True )     
    observacoes         =       models.TextField    (   null=False, blank=False)

pet_app/models/pet_models.py
from django.db import models
from django.db.models.deletion import CASCADE
from ..models import cliente_models



class TimeStampedModel(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        abstract = True


class Pet(TimeStampedModel):    
    CATEGORIA_PET_CHOICES = (
        ('Ca', 'Cachorro'),
        ('Ga', 'Gato'),
        ('Pa', 'Pássaro'),
        ('Ha', 'Hamister'),
    )        

    COR_PET_CHOICES = (
        ('Pr', 'Preto'),
        ('Br', 'Branco'),
        ('Ci', 'Cinza'),
        ('Ma', 'Malhado'),
        ('Cr', 'Creme'),
        ('Mr', 'Marrom'),
        ('Am', 'Amarelo'),
    )

    GENERO_PET_CHOICES = (
        ('Fe', 'Femea'),
        ('Ma', 'Macho'),
    )

    nome            =          models.CharField     (    max_length=50, null=False, blank=False  )
    idade           =          models.IntegerField  (    blank=False, null=False )
    peso            =          models.CharField     (    max_length=50, null=False, blank=False  )
    categoria       =          models.CharField     (    max_length=2, choices=CATEGORIA_PET_CHOICES, blank=True, null=True  )
    cor             =          models.CharField     (    max_length=2, choices=COR_PET_CHOICES, blank=True, null=True    )
    raca            =          models.CharField     (    max_length=20, blank=True, null=True    )
    genero          =          models.CharField     (    max_length=2, choices=GENERO_PET_CHOICES, blank=True, null=True )
    proprietario    =          models.ForeignKey    (    cliente_models.Cliente, on_delete=models.CASCADE, blank=False, null=False  )


#-----------------------ainda em ajuste para que não haja pets duplicados
    # def clean(self):  
    #     error_messages = {}      
    #     nome_pet_enviado = self.nome or None
    #     nome_pet_salvo = None
    #     pet = Pet.objects.filter(nome=nome_pet_enviado).first()        
    #     if pet:
    #         nome_pet_salvo = pet.nome
    #         if nome_pet_salvo is not None and self.id != pet.id:
    #             error_messages['nome'] = 'Nome do Pet já existe'
    # class Meta:
    #     constraints = [models.UniqueConstraint(name='my_pet_unique_constraint', fields = ['nome', 'proprietario'])]   
#------------------------------------------------------------------------   

pet_app/forms/cliente_forms.py
from django import forms
from django.forms import widgets, DateInput
from ..models import cliente_models

#criando o forms do cliente com tudo o que será renderizado dentro do formulário

class ClienteForm(forms.ModelForm):
    class Meta:
        model = cliente_models.Cliente
        fields = ['nome', 'email', 'data_nascimento', 'cpf', 'profissao']
        widgets = {
            'data_nascimento': DateInput(
                attrs={'type': "date"}
            )
        }
        

pet_app/forms/consulta_forms.py
from django import forms
from ..models import consulta_models


class ConsultaPetForm(forms.ModelForm):
    class Meta:
        model = consulta_models.ConsultaPet
        fields = '__all__'
        exclude = ['pet', 'data']

pet_app/forms/contato_forms.py
from django import forms
from ..models import contato_models


class ContatoForm(forms.ModelForm):
    class Meta:
        model = contato_models.Contato
        fields = '__all__'
        widgets = {'telefone': forms.TextInput(attrs={'data-mask':"00-00000-0000"})}

pet_app/views/autenticacao_views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def login_usuario(request):
    if request.method == "POST":
        form_login = AuthenticationForm(data=request.POST)
        if form_login.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            usuario = authenticate(request, username=username, password=password)
            if usuario is not None:
                login(request, usuario)
                return redirect('listar_clientes')
            else:
                messages.error(request, "As credenciais inseridas estão incorretas")
                return redirect('login')
    else:
        form_login = AuthenticationForm()
    return render(request, 'autenticacao/login.html', {'form_login': form_login})



#@login_required()
def deslogar_usuario(request):
    logout(request)
    return redirect('login')

pet_app/views/cliente_views.py
from django.shortcuts import redirect, render
from ..forms.cliente_forms import ClienteForm
from ..forms.endereco_forms import EnderecoClienteForm
from ..entidades import cliente, endereco
from ..services import cliente_service, endereco_service, pet_service, consulta_service
from django.contrib.auth.decorators import login_required, user_passes_test


#@login_required() #verifica se tem algum user logado
#se sim ele entra na página, se nao ele não permite a entrada.
def listar_clientes(request):
    clientes        =       cliente_service.listar_clientes()
    #todos os clientes cadastrados no banco de dados
    return render(request, 'clientes/lista_clientes.html', {'clientes': clientes})

def listar_cliente_id(request, id):
    cliente         =       cliente_service.listar_cliente_id(id)
    pets            =       pet_service.listar_pets(id)
    consultas       =       consulta_service.listar_consultas_pets(id)
    return render(request, 'clientes/lista_cliente.html', {'cliente': cliente, 
                                                            'pets': pets, 
                                                            'consultas': consultas})

#@login_required()
def cadastrar_cliente(request):
    if request.method == "POST":
        form_cliente        =       ClienteForm(request.POST)
        form_endereco       =       EnderecoClienteForm(request.POST)
        if form_cliente.is_valid():
            nome                    =       form_cliente.cleaned_data["nome"]
            email                   =       form_cliente.cleaned_data["email"]
            cpf                     =       form_cliente.cleaned_data["cpf"]
            data_nascimento         =       form_cliente.cleaned_data["data_nascimento"]
            profissao = form_cliente.cleaned_data["profissao"]
            if form_endereco.is_valid():
                rua                     =       form_endereco.cleaned_data["rua"]
                cidade                  =       form_endereco.cleaned_data["cidade"]
                estado                  =       form_endereco.cleaned_data["estado"]
                endereco_novo           =       endereco.Endereco(rua=rua, cidade=cidade, estado=estado)
                endereco_bd             =       endereco_service.cadastrar_endereco(endereco_novo)
                cliente_novo            =       cliente.Cliente(nome=nome, 
                                                                email=email, 
                                                                data_nascimento=data_nascimento,
                                                                profissao=profissao, 
                                                                cpf=cpf, 
                                                                endereco=endereco_bd)
                cliente_service.cadastrar_cliente(cliente_novo)
                return redirect('listar_clientes')
    else:
        form_cliente        =        ClienteForm()
        form_endereco       =        EnderecoClienteForm()
    return render(request, 'clientes/form_cliente.html', {'form_cliente': form_cliente,
                                                            'form_endereco': form_endereco})


#@login_required()
def remover_cliente(request, id):
    cliente         =       cliente_service.listar_cliente_id(id)
    endereco        =       endereco_service.listar_endereco_id(cliente.endereco.id)
    if request.method == "POST":
        cliente_service.remover_cliente(cliente)
        endereco_service.remover_endereco(endereco)
        return redirect('listar_clientes')
    return render(request, 'clientes/confirma_exclusao.html', {'cliente': cliente})


#@login_required()
def editar_cliente(request, id):
    cliente_editar          =           cliente_service.listar_cliente_id(id)
    form_cliente            =           ClienteForm(request.POST or None, instance=cliente_editar)
    endereco_editar         =           endereco_service.listar_endereco_id(cliente_editar.endereco.id)
    form_endereco           =           EnderecoClienteForm(request.POST or None, instance=endereco_editar)
    if form_cliente.is_valid():
            nome                    =       form_cliente.cleaned_data["nome"]
            email                   =       form_cliente.cleaned_data["email"]
            cpf                     =       form_cliente.cleaned_data["cpf"]
            data_nascimento         =       form_cliente.cleaned_data["data_nascimento"]
            profissao               =       form_cliente.cleaned_data["profissao"]
            if form_endereco.is_valid():
                        rua                 =       form_endereco.cleaned_data["rua"]
                        cidade              =       form_endereco.cleaned_data["cidade"]
                        estado              =       form_endereco.cleaned_data["estado"]
                        endereco_novo       =       endereco.Endereco(rua=rua, cidade=cidade, estado=estado)
                        endereco_editado    =       endereco_service.editar_endereco(endereco_editar, endereco_novo)
                        cliente_novo        =       cliente.Cliente(nome=nome, 
                                                        email=email, 
                                                        data_nascimento=data_nascimento,
                                                        profissao=profissao, 
                                                        cpf=cpf, 
                                                        endereco=endereco_editado)
                        cliente_service.editar_cliente(cliente_editar, cliente_novo)
                        return redirect('listar_clientes')
    return render(request, 'clientes/form_cliente.html', {'form_cliente':form_cliente, 
                                                        'form_endereco': form_endereco})

pet_app/views/consulta_views.py
from django.contrib.auth import login
from ..forms import consulta_forms
from ..services import pet_service, consulta_service
from django.shortcuts import render, redirect
from ..entidades import consulta
from django.contrib.auth.decorators import login_required, user_passes_test


#@user_passes_test(lambda u : u.cargo == 1) #somente usuarios (u) em que o cargo for = 1 poderão inserir
def inserir_consulta(request, id):
    if request.method       ==      "POST":
        form_consulta       =       consulta_forms.ConsultaPetForm(request.POST)
        pet                 =       pet_service.listar_pet_id(id)
        if form_consulta.is_valid():
            motivo_consulta                 =       form_consulta.cleaned_data["motivo_consulta"]
            medicamento_atual               =       form_consulta.cleaned_data["medicamento_atual"]
            medicamentos_prescritos         =       form_consulta.cleaned_data["medicamentos_prescritos"]
            exames                          =       form_consulta.cleaned_data["exames"]
            especialidade                   =       form_consulta.cleaned_data["especialidade"]
            doutor                          =       form_consulta.cleaned_data["doutor"]
            observacoes                     =       form_consulta.cleaned_data["observacoes"]
            consulta_nova                   =       consulta.ConsultaPet(  pet=pet, 
                                                                motivo_consulta=motivo_consulta, 
                                                                medicamento_atual=medicamento_atual,
                                                                medicamentos_prescritos=medicamentos_prescritos, 
                                                                exames=exames, 
                                                                especialidade=especialidade, 
                                                                doutor=doutor,
                                                                observacoes=observacoes  )
            consulta_service.cadastrar_consulta(consulta_nova)
            return redirect('listar_pet_id', pet.id)
    else:
        form_consulta       =       consulta_forms.ConsultaPetForm()
    return render(request, 'consultas/form_consulta.html', {'form_consulta': form_consulta})


#@login_required()
def listar_consulta_id(request, id):
    consulta        =       consulta_service.listar_consulta(id)
    return render(request, 'consultas/lista_consulta.html', {'consulta': consulta})

pet_app/views/dashboard_views.py
from django.shortcuts import render


def dashboard(request):
    return render(request, 'dashboard.html')

pet_app/templates/consultas/form_consulta.html
{% extends "base.html" %}
{% load meus_filtros %}
{% block title %}
Cadastro de Consulta
{% endblock title %}

{% block content %}
<div class="box box-primary" style="border-radius: 15px; margin-left: 20px;">
    <div class="box-header with-border">
        <div class="card-title"><h3>            
            <b>CADASTRO DE CONSULTAS</b>            
        </div>    
    </div>    
    <br>
    <div class="box-body">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form_consulta.motivo_consulta.errors }}
                <label>MOTIVO DA COSULTA: </label>
                {{ form_consulta.motivo_consulta|addclass:'form-control'}}
            </div>

            <div class="form-group">
                {{ form_consulta.especialidade.errors }}
                <label>ESPECIALIDADE: </label>
                {{ form_consulta.especialidade|addclass:'form-control'}}
            </div>

            <div class="form-group">
                {{ form_consulta.doutor.errors }}
                <label>DOUTOR: </label>
                {{ form_consulta.doutor|addclass:'form-control' }}
            </div>

            <div class="form-group">
                {{ form_consulta.medicamento_atual.errors }}
                <label>MEDICAMENTO ATUAL: </label>
                {{ form_consulta.medicamento_atual|addclass:'form-control'}}
            </div>
            <div class="form-group">
                {{ form_consulta.medicamentos_prescritos.errors }}
                <label>MEDICAMENTOS PRESCRITOS: </label>
                {{ form_consulta.medicamentos_prescritos|addclass:'form-control'}}
            </div>

            <div class="form-group">
                {{ form_consulta.exames.errors }}
                <label>EXAMES PRESCRITOS: </label>
                {{ form_consulta.exames|addclass:'form-control'}}
            </div>

            <div class="form-group">
                {{ form_consulta.observacoes.errors }}
                <label>OBSERVAÇÕES: </label>
                {{ form_consulta.observacoes|addclass:'form-control'}}
            </div>

            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>
{% endblock content %}

pet_app/templates/consultas/lista_consulta.html
{% extends "base.html" %}
{% load meus_filtros %}
{% block title %}
LISTA DE CONSULTAS
{% endblock title %}

{% block content %}

<div class="box box-primary" style="border-radius: 15px; margin-left: 20px;">
    <div class="box-header" style="margin-left: 20px;">
        <h2 class="page-header">
            <i class="fa fa-drivers-license"></i> <b>RESUMO DA CONSULTA</b><br>
            <br>
            <small class="pull-left"><b>Realizado em:</b> {{consulta.data}}</small><br>
            </h2>
    </div> 
    <div class="row invoice-info" style="margin-left: 20px;">        
        <div class="col-sm-4 invoice-col">
            <i class="fa fa-paw"></i><b>  DADOS DO PET</b>
            <HR>            
            <b>Nome: </b> {{consulta.pet.nome|title}} <br>
            <b>Categoria: </b> {{consulta.pet.get_categoria_display}} <br>
            <b>Idade: </b> {{consulta.pet.idade}} ano(s)<br>
            <b>Peso: </b> {{consulta.pet.peso}} kilo(s)<br>
            <b>Cor: </b>{{consulta.pet.get_cor_display}}<br>
            <b>Gênero: </b>{{consulta.pet.get_genero_display}}<br>
            <b>Raça: </b>{{consulta.pet.raca|upper}}<br>
            <b>Proprietário:</b> {{consulta.pet.proprietario.nome|title}}        
        </div>
    </div>
    <hr>
    <div class="row" style="margin-left: 20px;">
        <div class="col-sm-12">
            <i class="fa fa-bars"></i><b> DADOS DA CONSULTA</b>
            <hr>
            <b>Data da Consulta:</b> {{consulta.data}} <br>
            <b>Motivo da Consulta: </b> {{consulta.motivo_consulta|title}} <br>  
            <b>Médico Veterinário:</b> {{consulta.get_doutor_display}} <br>
            <b>Especialidade:</b> {{consulta.get_especialidade_display}} <br>                    
            <b>Medicamentos Prescritos: </b> {{consulta.medicamentos_prescritos}} <br>
            <b>Medicamentos Atuais: </b> {{consulta.medicamento_atual}} <br>
            <b>Exames Prescritos: </b> {{consulta.exames}} <br>
            <b>Observações: </b> {{consulta.exames}} <br>            
        </div>
    </div>
    <hr>
    <div class="row no-print" style="margin-left: 20px;">
        <div class="col-xs-12">
            <button type="button" class="btn btn-primary pull-left" onclick="window.print();">
                <i class="fa fa-print"> Imprimir</i>
            </button>
        </div>
    </div><br><br>    
</div> 

{% endblock content %}